name: Update Bin Collection Data

on:
  schedule:
    - cron: '0 2 * * MON'  # Runs at 2am every Monday
  workflow_dispatch:  # Allows manual triggering for testing

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install puppeteer
        
      - name: Run bin collection script
        run: node bins.js
        
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add binCollections.json
          git commit -m "Update bin collection data" -a || exit 0
          git push
